#!/bin/bash

LOCAL_PATH=$(pwd)

function fix_dependency {
    if [ -z "$1" ]; then
        echo "Something went wrong, I can't install nothing, can I??"; 
    else
        SECOND=$2
        if [ !$2 ]; then
            SECOND=$1
        fi

        hash $1 2>/dev/null || sudo apt-get install $SECOND;
    fi
}

function backup_if_needed {
    if [ -e $1 ]; then
        if [ -z "$2" ]; then
		    echo "Backing up old $2";
        else
		    echo "Backing up old file: $1";
        fi

		mv $1 $1.BACKUP
	fi
}

function create_link {
    echo "Creating link from $1 to $2"
    if [ -n "$1$2" ]; then
        $3 ln -s $1 $2
    fi
}

function print_start {
   echo "Installing [$1]";
}

function print_done {
   echo "Done with [$1]"; 
}

function install_git {
	echo "Installing git...";

    fix_dependency git
    backup_if_needed $HOME/.gitconfig gitconfig
	create_link $LOCAL_PATH/git/gitconfig $HOME/.gitconfig
}

function install_vim {

	echo "Installing vim...";

	backup_if_needed $HOME/.vimrc vimrc
	backup_if_needed $HOME/.vim "vim folder"
	create_link $LOCAL_PATH/vim/vimrc $HOME/.vimrc
	create_link $LOCAL_PATH/vim/vim $HOME/.vim
}

function install_zsh {

  echo "Installing zsh and oh-my-zsh..."

  backup_if_needed $HOME/.zshrc zshrc
  backup_if_needed $HELP/.oh-my-zsh
  create_link $LOCAL_PATH/zsh/zshrc $HOME/.zshrc
  create_link $LOCAL_PATH/zsh/oh-my-zsh $HOME/.oh-my-zsh
}

HELP=false

LAPTOP=false
DESKTOP=false

XMONAD=false
VIM=false
GIT=false
ZSH=false

ALL=false

while getopts ldaxvgzh option
do
  case "${option}"
  in
    l) LAPTOP=true;;
    d) DESKTOP=true;;
    a) ALL=true;;
	  x) XMONAD=true;;
		v) VIM=true;;
		g) GIT=true;;
		z) ZSH=true;;
	  h) HELP=true;;
  esac
done

if ($ALL); then
	XMONAD=true;
	VIM=true;
	GIT=true;
	ZSH=true;
fi

if ($HELP); then
	echo "Options:";
  echo "You can\'t have any help :\)"
else

	if ($LAPTOP && $DESKTOP); then
		echo "You can\'t install both the laptop and desktop version!";
	elif ($XMONAD && !($LAPTOP) && !($DESKTOP)); then
		echo "You must install either the laptop or desktop version!";
	else
		if ($XMONAD); then
			install_xmonad_common;
			if ($LAPTOP); then
				install_xmonad_laptop;
			elif ($DESKTOP); then
				install_xmonad_desktop;
			fi
		fi
		if ($VIM); then
			install_vim;
		fi
		if ($GIT); then
			install_git;
		fi
		if ($ZSH); then
			install_zsh;
		fi
	
		echo "Done!"
	fi
fi

