#!/bin/bash

BOLD="\033[1m"
NORMAL="\033[0m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"

LOCAL_PATH=$(pwd)

function info_message {
echo -e $BLUE"Info: " $NORMAL"$1" 
}

function warning_message {
echo -e $YELLOW"Warning: " $NORMAL"$1" 
}

function error_message {
echo -e $RED"Error: " $NORMAL"$1" 
}

function fix_dependency {
if [ -z "$1" ]; then
  echo "Something went wrong, I can't install nothing, can I??"; 
else
  SECOND=$2
  if [ !$2 ]; then
    SECOND=$1
  fi

  hash $1 2>/dev/null || sudo apt-get install $SECOND;
fi
}

function install_all_base_programs {
	fix_dependency "vim";
	fix_dependency "zsh";
	fix_dependency "xclip";
	fix_dependency "tmux";
	fix_dependency "git";
	fix_dependency "xmonad";
	fix_dependency "xmobar";
	fix_dependency "conky-all";
	fix_dependency "dmenu";
	fix_dependency "cmake";
	fix_dependency "make";
	fix_dependency "g++";
	fix_dependency "feh";
}

function backup_if_needed {

if [ -e $1 ]; then
  if ( $NO_BACKUP ); then
    CMD="$3 rm -r $1"
  else 
    CMD="$3 rm $.BACKUP && $3 mv $1 $1.BACKUP"
    if [ $2 ]; then
      echo "Backing up old $2";
    else
      echo "Backing up old file: $1";
    fi
  fi
fi
}

function remove_if_needed {
if [ -e $1 ]; then
  echo "Removing: $1"
  sudo rm -r $1
fi
}

function create_link {
CMD="ln -fsn"
echo "Creating link from $1 to $2"
if [ $2 ]; then
  $3 $CMD $1 $2
fi
}

function print_start {
echo -e $GREEN"Installing "$NORMAL"["$YELLOW$1$NORMAL"]";
}

function print_done {
#echo "Done with [$1]!"; 
echo  
}

function install_git {
print_start git
fix_dependency git
backup_if_needed $HOME/.gitconfig gitconfig
backup_if_needed $HOME/.gitignore gitignore

create_link $LOCAL_PATH/git/gitconfig $HOME/.gitconfig
create_link $LOCAL_PATH/git/gitignore $HOME/.gitignore
print_done git
}

function install_vim {
print_start vim
fix_dependency vim
backup_if_needed $HOME/.vimrc .vimrc
backup_if_needed $HOME/.vim .vim
create_link $LOCAL_PATH/vim/vimrc $HOME/.vimrc
create_link $LOCAL_PATH/vim/vim $HOME/.vim
print_done vim
}

function install_zsh {
print_start zsh
fix_dependency zsh
backup_if_needed $HOME/.zshrc .zshrc
backup_if_needed $HOME/.oh-my-zsh .oh-my-zsh
backup_if_needed $HOME/.tmux.conf .tmux.conf
create_link $LOCAL_PATH/zsh/zshrc $HOME/.zshrc
create_link $LOCAL_PATH/zsh/oh-my-zsh $HOME/.oh-my-zsh
create_link $LOCAL_PATH/tmux/tmux.conf $HOME/.tmux.conf
create_link $LOCAL_PATH/zsh/sh_functions $HOME/.sh_functions
touch $HOME/.aliases $HOME/.paths
print_done zsh
}

function install_xmonad {
print_start xmonad
fix_dependency xmonad
fix_dependency xmobar
fix_dependency conky-all
fix_dependency dmenu

remove_if_needed /usr/share/xsessions/xmonad.desktop
remove_if_needed /usr/local/bin/xmonad-startup
remove_if_needed $HOME/.ghci

backup_if_needed $HOME/.xmonad .xmonad
create_link $LOCAL_PATH/xmonad $HOME/.xmonad
create_link $LOCAL_PATH/xmonad/xmonad.desktop /usr/share/xsessions/xmonad.desktop sudo 
create_link $LOCAL_PATH/xmonad/xmonad-startup /usr/local/bin/xmonad-startup sudo
create_link $LOCAL_PATH/haskell/ghci $HOME/.ghci

backup_if_needed $HOME/.conkyrc .conkyrc
create_link $LOCAL_PATH/conky/conkyrc $HOME/.conkyrc

touch $HOME/.dmenu_favourites

backup_if_needed $HOME/.xmobarrc .xmobarrc
create_link $LOCAL_PATH/xmonad/xmobarrc $HOME/.xmobarrc

backup_if_needed $HOME/.initrc .xinitrc
create_link $LOCAL_PATH/xorg/xinitrc $HOME/.xinitrc

print_done xmonad
}

function install_term {
print_start xorg
fix_dependency urxvt rxvt-unicode-256color
XRC_NAME=Xresources
backup_if_needed $HOME/.$XRC_NAME .$XRC_NAME
create_link $LOCAL_PATH/xorg/$XRC_NAME $HOME/.$XRC_NAME 
xrdb $HOME/.$XRC_NAME

backup_if_needed $HOME/.xinitrc .xinitrc
create_link $LOCAL_PATH/xorg/xinitrc $HOME/.xinitrc 
print_done xorg
}

function install_irssi {
print_start irssi
fix_dependency irssi
# Since we don't want to version control our real irssi config (which could 
# contain your password and what not) we'll begin with copying the example 
# config.
if [ ! -e $LOCAL_PATH/irssi/config ]; then
  cp $LOCAL_PATH/irssi/config{.example,}
fi

backup_if_needed $HOME/.irssi .irssi
create_link $LOCAL_PATH/irssi $HOME/.irssi
print_done irssi
}

NO_BACKUP=false
HELP=false

XMONAD=false
VIM=false
GIT=false
ZSH=false
TERM=false
IRSSI=false
ALL=false

while getopts axvgztih! option
do
  case "${option}"
    in
a) ALL=true;;
    x) XMONAD=true;;
  v) VIM=true;;
g) GIT=true;;
    z) ZSH=true;;
  t) TERM=true;;
i) IRSSI=true;;
h) HELP=true;;
  !) NO_BACKUP=true;;
  esac
done

if ($ALL); then
  XMONAD=true;
  VIM=true;
  GIT=true;
  ZSH=true;
  TERM=true;
  IRSSI=true;
  install_all_base_programs;
fi

if ($HELP); then
  echo -e "$BOLD
  Options:$NORMAL

  a) Installs everything, has to be followed by one of -l or -d
  g) Intalls gitconfig
  h) Shows this help page
  i) Installs irssi config
  t) Installs Xorg resources, mainly used by URxvt
  v) Installs vimrc and plugins
  x) Installs xmonad configs
  z) Installs zshrc and oh-my-zsh
  !) Skip backup of conflicting files (use with caution)
  $BOLD
  Examples:$NORMAL

  ./install -vzg # Will install vim + plugins, zsh + oh-my-zsh and gitconfig
  ./install -xlv # Will install xmonad base, xmonad laptop and vim + plugins 
  ./install -ad  # Will install everything for desktop
  "
else
    if ($XMONAD); then
      install_xmonad;
    fi
    if ($VIM); then
      install_vim;
    fi
    if ($GIT); then
      install_git;
    fi
    if ($ZSH); then
      install_zsh;
    fi
    if ($TERM); then
      install_term;
    fi
    if ($IRSSI); then
      install_irssi;
    fi
    if ($XMONAD || $TERM || $VIM || $GIT || $YI || $ZSH || $IRSSI); then
      info_message "Done!"
    else
      warning_message "Nothing was installed. Try ./install -h?"
    fi
fi

