"============ Searching ============"
"Highlight searches by default"
set hlsearch
set showmatch
set incsearch

"============ Tab width ============"
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab "Makes vim substitute tab character with spaces"
set smartindent
set autoindent
set showbreak=...


"============ Swap files ============"
"No swap files"
set noswapfile
set nobackup
set nowb

"============ Movement ============"
"Move one row instead of one line"
" nmap j gj
" nmap k gk 

"============ Auto completion ============"
set wildmenu
set wildmode=list:longest,full

"============ Cursor ============"
if has("autocmd")
  au InsertEnter * set cul
  au InsertLeave * set nocul 
endif

set nocompatible

" Pathogen
call pathogen#infect()
call pathogen#helptags()
 
set statusline=%<\ %n:%f\ %m%r%y%=%-35.(line:\ %l\ of\ %L,\ col:\ %c%V\ (%P)%)
filetype plugin indent on
 
"========== Theme ============"
if has('unnamedplus')
	set clipboard=unnamedplus
else
	set clipboard=unnamed
endif

set number
syntax enable
set background=dark
colorscheme delek 
set t_Co=16

"============ Page width ============"
set textwidth=80
hi ColorColumn ctermbg=None
hi ColorColumn ctermfg=Red
execute "set colorcolumn=" . join(range(81,200), ',')

"========== Map ============"
command Q q

"== Unmap arrow keys =="
map <up>	<nop>
map <down>	<nop>
map <left>	<nop>
map <right> <nop>

let mapleader=","
nmap <silent> ,/ :nohlsearch<CR>

"map ,s :w<CR>
"map ,q :q<CR>

"== w!! to sudo write =="
cmap w!! w !sudo tee % >/dev/null

