#!/bin/bash

# ssh-agent
eval $(ssh-agent)
nm-applet &

# Set cursor
xset s offxsetroot -cursor_name left_ptr

# Set fonts, colors etc for urxvt
xrdb ~/.Xresources

# Set primary screen
xrandr --output DP-4 --primary
xrandr --output DP-4 --left-of DVI-I-1

# Svdvorak :)
setxkbmap "us(dvorak-intl)"
# Swap CapsLock for Escape
echo "clear Lock\nkeycode 0x42 = Escape\n" | xmodmap -
synclient TapButton1=1 TapButton2=3 TapButton3=2 PalmDetect=1

# Set BG
feh /home/john/Pictures/BGs/black-cats-awesomelycute.com-25.jpg --bg-fill

# Start WM
conky
xmonad
