#!/bin/bash

# ssh-agent
eval $(ssh-agent)
nm-applet &

# Set cursor
xset s offxsetroot -cursor_name left_ptr

# Set fonts, colors etc for urxvt
xrdb ~/.Xresources

# Set primary screen
xrandr --output DP-0 --primary
xrandr --output DP-3 --left-of DP-0

# Trackman settings
xinput --set-prop 14 294 0, 0, 1
xinput --set-prop 14 302 1.0

# Set BG
feh $(ls /home/user/some_path/to/backgrounds/* | shuf -n 1) --bg-fill

# Start dunst (show notifications)
dunst &

# Start WM
xmonad
