#!/bin/bash

# ssh-agent
eval $(ssh-agent)
nm-applet &

# Set cursor
xset s offxsetroot -cursor_name left_ptr

# Svdvorak :)
setxkbmap "se(svdvorak)"
echo "clear Lock\nkeycode 0x42 = Escape\n" | xmodmap -
xrdb ~/.Xresources

# Start WM
conky
xmonad
