#!/bin/bash

eval $(ssh-agent)

eval $(gnome-keyring-daemon --start --components keyring,pkcs11)
export GNOME_KEYRING_SOCKET
export GNOME_KEYRING_PID
nm-applet &

xsetroot -cursor_name left_ptr
setxkbmap "se(svdvorak)" &
xrdb ~/.Xresources
xmonad
