#!/bin/bash

function var_or_default() {
    if [ -z ${(P)1} ]; then
        echo $2
    else
        echo ${(P)1}
    fi
}

function _generic_note() {
    local NAME="$1"
    local NAME_UC=`echo "$1" | tr '[:lower:]' '[:upper:]'`
    local DIR_NAME="`var_or_default XDG_DATA_HOME $HOME/.local/share`/$NAME";
    local FILE_NAME="";
    case $2 in
        '-d') FILE_NAME="$DIR_NAME/$NAME"_"$(date +%F)".md;;
        '-c') echo 'Clearing empty files';
              IFS="
"
              for f in $(ls -1 "$DIR_NAME"); do
                  if [[ $(wc -l "$DIR_NAME/$f" | awk '{ print $1 }') == 4 ]]; then
                      echo "$f appears to be empty. [v]iew [c]lear or [i]gnore?: ";
                      read ANSWER;
                      case $ANSWER in
                        'v'|'V') cat "$DIR_NAME/$f";
                                 print "[c]lear or [i]gnore?: ";
                                 read ANSWER;
                                 case $ANSWER in
                                    'c'|'C') rm "$DIR_NAME/$f";;
                                 esac
                                 ;;
                        'c'|'C') rm "$DIR_NAME/$f";;
                      esac
                  fi
              done
              return;;
        *) FILE_NAME="$DIR_NAME/$NAME.md";;
    esac

    if [[ ! -d "$DIR_NAME" ]]; then
        mkdir "$DIR_NAME";
    fi


    if [[ ! -f "$FILE_NAME" ]]; then
        echo "# $NAME_UC\n\nCreated: $(date +%F)\n" >> "$FILE_NAME"
    fi

    vim "$FILE_NAME" +;
}

function todo() {
    _generic_note todo $@
}

function notes() {
    _generic_note note $@
}

function monitor_sensors() {
  while true; do
    clear;
    sudo sensors;
    for i in {1..10}; do
      printf .;
      sleep 1;
    done;
  done
}

function net_slow() {
  local file="/tmp/net_slow"
  if [ -f "$file" ]; then
    local delay=$(cat "$file" | tr -cd '[:digit:]');
    echo "Deleting network delay $delay""ms";
    sudo tc qdisc del dev eth0 root netem delay "$delay"ms;
    rm "$file";
  fi
  if [[ "$1" != "" ]]; then
    echo "Adding network delay $1""ms";
    printf "$1" > "$file"
    sudo tc qdisc add dev eth0 root netem delay "$1"ms;
  fi
  #sudo tc qdisc del dev eth0 root netem delay 10000ms
}

function cesc() {
    xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
}

function ccaps() {
    xmodmap -e 'clear Lock' -e 'keycode 0x42 = Caps_Lock'
}

# Plays a sound effect depending on the exit status of the previously ran command
# Expects there to be two files/symlinks in ~/.config/boop/{good,bad}.wav
function boop() {
    # Inspired by https://gitlab.com/EvanHahn/dotfiles/-/blob/ece393e625bb8254fe05774df33bb5af8a73d7e7/home/zsh/.config/zsh/aliases.zsh#L48-56
    local last="$?"
    if [[ "$last" == '0' ]]; then
        sfx good
    else
        sfx bad
    fi
    $(exit "$last")
}

function gclone() {
    case "$1" in
        --https) REPO="https://github.com/$2";;
        --ssh) REPO="git@github.com:$2";;
        *) REPO="https://github.com/$1";;
    esac
    git clone "$REPO"
}
