#!/bin/bash

function todo() {
    local DIR_NAME="$HOME/.todo";
    local FILE_NAME="";
    case $1 in
        '-d') FILE_NAME="$DIR_NAME/todo_$(date +%F).md";;
        '-c') echo 'Clearing empty todos';
              IFS="
"
              for f in $(ls -1 "$DIR_NAME"); do
                  if [[ $(wc -l "$DIR_NAME/$f" | awk '{ print $1 }') == 4 ]]; then
                      echo "$f appears to be empty. [v]iew [c]lear or [i]gnore?: ";
                      read ANSWER;
                      case $ANSWER in
                        'v'|'V') cat "$DIR_NAME/$f";
                                 print "[c]lear or [i]gnore?: ";
                                 read ANSWER;
                                 case $ANSWER in
                                    'c'|'C') rm "$DIR_NAME/$f";;
                                 esac
                                 ;;
                        'c'|'C') rm "$DIR_NAME/$f";;
                      esac
                  fi
              done
              return;;
        *) FILE_NAME="$DIR_NAME/todo.md";;
    esac

    if [[ ! -d "$DIR_NAME" ]]; then
        mkdir "$DIR_NAME";
    fi


    if [[ ! -f "$FILE_NAME" ]]; then
        echo "# TODO\n\nCreated: $(date +%F)\n" >> "$FILE_NAME"
    fi

    vim "$FILE_NAME" +;
}

function monitor_sensors() {
  while true; do
    clear;
    sudo sensors;
    for i in {1..10}; do
      printf .;
      sleep 1;
    done;
  done
}

function net_slow() {
  local file="/tmp/net_slow"
  if [ -f "$file" ]; then
    local delay=$(cat "$file" | tr -cd '[:digit:]');
    echo "Deleting network delay $delay""ms";
    sudo tc qdisc del dev eth0 root netem delay "$delay"ms;
    rm "$file";
  fi
  if [[ "$1" != "" ]]; then
    echo "Adding network delay $1""ms";
    printf "$1" > "$file"
    sudo tc qdisc add dev eth0 root netem delay "$1"ms;
  fi
  #sudo tc qdisc del dev eth0 root netem delay 10000ms
}

function caps_esc() {
    xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
}

function caps_caps() {
    xmodmap -e 'clear Lock' -e 'keycode 0x42 = Caps_Lock'
}

function _silent_play() {
    if readlink -e "$1" >> /dev/null;
    then
        aplay "$1" 2>/dev/null
    else
        spd-say "Silent play couldn't find file $(basename \"$1\")"
    fi
}

# Plays a sound effect depending on the exit status of the previously ran command
# Expects there to be two files/symlinks in ~/.config/boop/{good,bad}.wav
function boop() {
    # Inspired by https://gitlab.com/EvanHahn/dotfiles/-/blob/ece393e625bb8254fe05774df33bb5af8a73d7e7/home/zsh/.config/zsh/aliases.zsh#L48-56
    local last="$?"
    if [[ "$last" == '0' ]]; then
        _silent_play "$HOME/.config/boop/good.wav"
    else
        _silent_play "$HOME/.config/boop/bad.wav"
    fi
    $(exit "$last")
}
