# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="jbarberu"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

function src_if_exists {
	if [ -e "$1" ]; then
		source "$1"
	fi
}

function src_if_os {
	if [ "$(uname)" = "$1" ]; then
		src_if_exists "$2";
	fi
}

function backup() {
  if type backer.py >> /dev/null; then
    backer.py
  else
    echo "backer.py not installed, do: echo \"export PATH=\$HOME/dotfiles/tools/backer_py:\$PATH\" >> \$HOME/.paths (or wherever you store the dotfiles)"
  fi
}

function maybe_backup() {
  if [ -e "$HOME/.backer.json" ]; then

    local ANS="n"

    local SETTINGS_FILE="$HOME/.backer-settings"
    if [ -e "$SETTINGS_FILE" ]; then
      if cat "$SETTINGS_FILE" | grep -e "[y,Y]" >> /dev/null; then
        ANS="y";
      fi
    else
      printf "Run backups? [Y/N] (add r for remember): "
      read read_ans
      if echo "$read_ans" | grep -e "[y,Y]" >> /dev/null; then
        ANS="y";
      else
        ANS="n"
      fi
    fi

    case "$ANS" in
      "y") backup;;
    esac

    if echo "$read_ans" | grep "r" >> /dev/null; then
      echo "$ANS" > "$SETTINGS_FILE";
    fi

  fi
}

function natti() {
  printf "Shut down $HOST? [Y/N]: "
  read ans

  if sudo -k && sudo echo "Got root permission"; then
    ;
  fi
  case $ans in
    "Y"|"y") maybe_backup; sudo shutdown -h now;;
  esac
}

case $(uname) in
  "Darwin")
      alias pubkey="cat ~/.ssh/id_rsa.pub | pbcopy | echo \"Copied public key to clipboard...\"";;
  "Linux")
      alias pubkey="cat ~/.ssh/id_rsa.pub | xclip -selection clipboard | echo \"Copied public key to clipboard...\"";
      alias dvorak="ibus exit &> /dev/null; setxkbmap \"se(svdvorak)\" && echo \"clear Lock\\nkeycode 0x42 = Escape\\n\" | xmodmap -";
      alias se="setxkbmap se && echo \"clear Lock\\nkeycode 0x42 = Escape\\n\" | xmodmap -";
      alias ag="sudo apt-get"
      alias sx="startx"
      ;;
esac

alias gs="git status 2> /dev/null || (echo \"Not a git repository, doing ls instead\n\" && ls)"
alias j="jump"
alias zshreload="source ~/.zshrc"
alias tmux="tmux -u"
alias cheat="cat $HOME/.cheat_sheet"
alias clip="CLIP=\"\$(xclip -o -selection clipboard)\" && echo Put the contents of clipboard into CLIP :\)"

src_if_exists "$HOME/.aliases"
src_if_exists "$HOME/.paths"
src_if_exists "$HOME/.env"
src_if_exists "$HOME/.osx_only"
src_if_exists "$HOME/.linux_only"
src_if_exists "$HOME/.sh_functions"
src_if_os "Darwin" "$HOME/.zshrc_osx"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(bundler cabal cp gem git jump rails web-search)
case "$(uname)" in
  "Darwin") plugins=($plugins brew);;
esac

source $ZSH/oh-my-zsh.sh
