#!/bin/bash

BOLD="\033[1m"
NORMAL="\033[0m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"

function create_file {
	echo -e $1 >> $2
}

function add_to_cmake {
	echo $1 >> $2/CMakeLists.txt
}

OPT_HEADER=false;
OPT_SOURCE=false;
OPT_BUILDSYS=false;

while getopts hcb option
do
  case "${option}"
    in
    h) OPT_HEADER=true;;
    c) OPT_SOURCE=true;;
	b) OPT_BUILDSYS=true;;
  esac
done

NUM_OPT=$((0))

if ($OPT_HEADER); then
	NUM_OPT=$(($NUM_OPT+1))
fi
if ($OPT_SOURCE); then
	NUM_OPT=$(($NUM_OPT+1))
fi
if ($OPT_BUILDSYS); then
	NUM_OPT=$(($NUM_OPT+1))
fi

FILE_NAME=""
FILE_PATH=""

if [ $NUM_OPT = 0 ]; then
	echo "Not doing anything..."	
else 
	if [ $NUM_OPT = 1 ]; then
		FILE_NAME=$2
		FILE_PATH=$3
	elif [ $NUM_OPT = 2 ]; then
		FILE_NAME=$3
		FILE_PATH=$4
	elif [ $NUM_OPT = 3 ]; then
		FILE_NAME=$4
		FILE_PATH=$5
	fi

	if ($OPT_HEADER); then
		create_file "#ifndef CLASS_H\n#define CLASS_H\n\nnamespace dreamler\n{\n\nnamespace some_namespace\n{\n\nclass $FILE_NAME\n{\npublic:\n\n};\n\n}\n}\n\n#endif //CLASS_H" $FILE_PATH/$FILE_NAME.h 
	fi
	if ($OPT_SOURCE); then
		create_file "#include \"stdafx.h\"\n#include \"$FILE_NAME.h\"\n\nnamespace dreamler\n{\nnamespace some_namespace\n{\n\n\n}\n}\n" $FILE_PATH/$FILE_NAME.cpp
	fi
	if ($OPT_BUILDSYS); then
		if ($OPT_HEADER); then
			add_to_cmake "$FILE_NAME.h" $FILE_PATH
		fi
		if ($OPT_SOURCE); then
			add_to_cmake "$FILE_NAME.cpp" $FILE_PATH
		fi
	fi
fi
